when:
  - event: pull_request
  - event: tag
  - event: push
    branch:
      - ${CI_REPO_DEFAULT_BRANCH}
      - renovate/*

variables:
  - &platforms "linux/amd64,linux/arm64,linux/s390x"
  - &buildx-plugin "coralhl/woodpecker-kaniko-plugin"
  # vars used on push / tag events only
  - publish_logins: &publish_logins
      # Default DockerHub login
      registry: docker.io
      username:
        from_secret: dockerhub_username
      password:
        from_secret: dockerhub_password
  - &publish_repos "coralhl/woodpecker-kaniko-plugin"

steps:
  lint:
    image: alpine:3.19
    commands:
      - apk add -U shellcheck
      - shellcheck -e SC3040 -e SC3010 -e SC3037 -e SC3020 -e SC2162 *.sh
    when:
      - event: pull_request
      - event: push
        branch: renovate/*

  # TODO: add test of fresh build kaniko

  build-dryrun:
    image: *buildx-plugin
    depends_on:
      - lint
    settings:
      repo: test/repo
      dry_run: true
      platforms: *platforms
      tags: latest
    when:
      - event: pull_request
      - event: push
        branch: renovate/*

  release-next:
    image: *buildx-plugin
    settings:
      repo: *publish_repos
      platforms: *platforms
      tags: next
      <<: *publish_logins
    when:
      branch: ${CI_REPO_DEFAULT_BRANCH}
      event: push

  release-tag:
    image: *buildx-plugin
    settings:
      repo: *publish_repos
      platforms: *platforms
      auto_tag: true
      # remove line below if you can read it on a release branch and it's not the latest release branch
      tags: latest
      <<: *publish_logins
    when:
      event: tag
